### ISSUE TITLE
Workflow template repo is not up to date with the latest Workflow API changes

### ISSUE THREAD

**Issue by donahuejw** [square/workflow-android-template#4]
Just today (12/5/19) I created a new repo from this template, and when I cloned my repo and opened the project in Android Studio I was immediately presented with multiple compilation issues.  The specific issues appear to be:

- import and usage of `com.squareup.workflow.ui.ExperimentalWorkflowUi`, which either no longer exists or has been renamed / moved to a new package
- The signature for the `LayoutRunner.showRendering()` method looks to have changed, but that has not been reflected in the `HelloLayoutRunner` class
- The signature for the `WorkflowRunner.setContentWorkflow()` method looks to have changed, but this has not been reflected in the `HelloWorkflowActivity` class

**Comment by donahuejw** [comment]
Realized that the repo does actually compile as is since the Workflow version in build.gradle is pinned to one where the API is still compatible.  It broke for me because after opening the project in Android Studio I accepted an automatic prompt to update to the latest Workflow version, which is **not** compatible.  So, it's still good to update this app to be compatible with the latest API, but it's not quite as critical since it does compile as is.

**Comment by forrestbice** [comment]
@donahuejw I just bumped dependencies: https://github.com/square/workflow-android-template/pull/5. Going to close this out but re-open if you still are having trouble. I'll try to keep this template up-to-date with new Workflow versions when I can.
